name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install otfcc
      run: |
        brew tap caryll/tap
        brew install otfcc-mac64
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Build
      run: |
        build/prepare.sh
        python build/main.py
    - name: Upload FanWunMing
      uses: actions/upload-artifact@v2
      with:
        name: FanWunMing
        path: |
          output/FanWunMing-*.ttf
          !output/FanWunMing-TW-*.ttf
    - name: Upload FanWunMing-TW
      uses: actions/upload-artifact@v2
      with:
        name: FanWunMing-TW
        path: output/FanWunMing-TW-*.ttf
